// <auto-generated />
namespace ourfitnessplan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addingallowhtmlforcontent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingallowhtmlforcontent));
        
        string IMigrationMetadata.Id
        {
            get { return "202204171024176_adding allow html for content"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
